WHENEVER SQLERROR EXIT SQL.SQLCODE

SET DEFINE ON

ALTER SESSION SET CURRENT_SCHEMA=&_vUsername
/

CREATE OR REPLACE PUBLIC SYNONYM TWOFACTOR FOR TWOFACTOR
/
CREATE OR REPLACE PUBLIC SYNONYM ENABLE_ROLE FOR ENABLE_ROLE
/

GRANT EXECUTE ON TWOFACTOR TO PUBLIC
/
GRANT EXECUTE ON ENABLE_ROLE TO PUBLIC
/
