WHENEVER SQLERROR EXIT SQL.SQLCODE

SET DEFINE ON

ALTER SESSION SET CURRENT_SCHEMA=&_vUsername
/

SET DEFINE OFF

CREATE OR REPLACE TRIGGER SET_TWOFACTOR_CTX_TRIG
  AFTER LOGON ON DATABASE
BEGIN
  -- Created by Rodrigo Jorge - www.dbarj.com.br --
  TWOFACTOR_INTERNAL.CHECKANDAUTHUSER;
EXCEPTION
  WHEN OTHERS THEN
    NULL;
END;
/
